### ISSUE TITLE
DNS-SD error msg in manual mode

### ISSUE THREAD

**Issue by pkeroulas** [garethsb/nmos-cpp-examples#3]
My current environment doesn't support DNS-SD, so I've just set `registry_address` and `registration_port` in the json conf, but no `domain`. The node registration is fine but I can't get rid of this periodic message.

```
DNSServiceBrowse reported error: -65537
Did not discover a suitable System API via DNS-SD
System API request HTTP error: Failed to connect to any resolved endpoint [generic:113]
System global configuration is not discoverable
```

**Comment by garethsb** [comment]
For the System API, you can use the configuration settings, `system_address` and `system_port` 
If you want to specify the API versions, you can use `registry_version` and `system_version`.

**Comment by pkeroulas** [comment]
Perfect, I didn't know that aspect for the registry, thanks!
